account/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("register", views.register, name="register"),
    path("edit", views.edit, name="edit"),
    path("users/", views.UserListView.as_view(), name="user_list"),
    path("users/<str:username>/", views.UserDetailView.as_view(), name="user_detail"),
    path("follow/", views.user_follow, name="user_follow"),
]

images/urls.py
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path("add/<int:place_id>/", views.AddImageView.as_view(), name="add"),
    path("delete/<int:pk>/", views.DeleteImageView.as_view(), name="delete"),
    path("list/<str:username>/", views.ImageListView.as_view(), name="list"),
    path("<int:pk>/<slug:slug>/", views.ImageDetailView.as_view(), name="detail"),
]

travelblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("images/", include("images.urls", namespace="images")),
    path("places/", include("places.urls", namespace="places")),
    path("articles/", include("articles.urls", namespace="articles")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("", include("account.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.db import models
from django.urls import reverse


class CustomUserManager(UserManager):
    def get_queryset(self):
        return super().get_queryset()

    def search_by_username(self, search_text):
        vector = SearchVector("username")
        query = SearchQuery(search_text)
        return (
            self.get_queryset()
            .annotate(search=vector, rank=SearchRank(vector, query))
            .filter(search=search_text)
            .order_by("-rank")
        )


class User(AbstractUser):
    following = models.ManyToManyField(
        "self", through="Follow", related_name="followers", symmetrical=False
    )
    objects = CustomUserManager()

    def get_absolute_url(self):
        return reverse("user_detail", args=[self.username])


class Follow(models.Model):
    user_from = models.ForeignKey(
        User, related_name="rel_from_set", on_delete=models.CASCADE
    )
    user_to = models.ForeignKey(
        User, related_name="rel_to_set", on_delete=models.CASCADE
    )
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"{self.user_from} follows {self.user_to}"

account/forms.py
from django import forms

from .models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords don't match.")
        return cd["password2"]


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")


class UserSearchForm(forms.Form):
    user_search = forms.CharField(label="Search", help_text="Search for users")

account/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView, ListView, DetailView

from articles.forms import ArticleSearchForm
from articles.models import Article
from common.decorators import ajax_required
from places.forms import PlaceSearchForm
from places.models import Place
from .forms import UserRegistrationForm, UserEditForm, UserSearchForm
from .models import User, Follow


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()
            return render(request, "account/register_done.html", {"new_user": new_user})
    user_form = UserRegistrationForm()
    return render(
        request,
        "account/register.html",
        {"user_form": user_form, "section": "register"},
    )


def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, "Profile updated successfully")
        else:
            messages.error(request, "Error updating your profile")
    else:
        user_form = UserEditForm(instance=request.user)
    return render(request, "account/edit.html", {"user_form": user_form})


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "account/dashboard.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        articles = None
        places = None
        if "place_search" in self.request.GET:
            place_search = self.request.GET["place_search"]
            places = Place.objects.search_by_name(place_search)
        elif "article_search" in self.request.GET:
            article_search = self.request.GET["article_search"]
            articles = Article.pub_objects.search_by_title(article_search)
        else:
            following_ids = self.request.user.following.values_list("id", flat=True)
            if following_ids:
                articles = Article.pub_objects.filter(
                    author_id__in=following_ids
                ).order_by("-publish")[:10]
            else:
                articles = Article.pub_objects.all().order_by("-publish")[:10]
        data["articles"] = articles
        data["places"] = places
        data["section"] = "dashboard"
        data["article_search_form"] = ArticleSearchForm()
        data["place_search_form"] = PlaceSearchForm()
        return data


class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "account/list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data()
        data["user_search_form"] = UserSearchForm()
        data["section"] = "users"
        return data

    def get_queryset(self):
        if "user_search" in self.request.GET:
            user_search = self.request.GET["user_search"]
            return User.objects.search_by_username(user_search)
        return super().get_queryset()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "account/detail.html"
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        data["article_search_form"] = ArticleSearchForm()
        data["place_search_form"] = PlaceSearchForm()
        data["section"] = "users"
        articles = None
        places = None
        if "place_search" in self.request.GET:
            place_search = self.request.GET["place_search"]
            places = Place.objects.search_by_name(place_search).filter(
                author=self.object
            )
        elif "article_search" in self.request.GET:
            article_search = self.request.GET["article_search"]
            articles = Article.pub_objects.search_by_title(article_search, articles)
        else:
            articles = Article.pub_objects.filter(author=self.object)
        data["articles"] = articles
        data["places"] = places
        return data


@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get("id")
    action = request.POST.get("action")
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            return JsonResponse({"status": "error"})
        else:
            if action == "follow":
                Follow.objects.get_or_create(
                    user_from=request.user,
                    user_to=user,
                )
            else:
                Follow.objects.filter(
                    user_from=request.user,
                    user_to=user,
                ).delete()
            return JsonResponse({"status": "ok"})
    return JsonResponse({"status": "error"})

account/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  {% block head %}
  {% endblock %}

  <title>
    {% block title %}
    {% endblock %}
  </title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <!-- Custom styles for this template -->
  {% load static %}
  <link href="{% static 'css/blog-post.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #d1eaf5;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'dashboard' %}">TravelBlog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item {% if section == 'dashboard' %}active{% endif %}">
            <a class="nav-link" href="{% url 'dashboard' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item {% if section == 'about' %}active{% endif %}">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item {% if section == 'groups' %}active{% endif %}">
            <a class="nav-link" href="#">Groups</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item {% if section == 'users' %}active{% endif %}">
              <a class="nav-link" href="{% url 'user_list' %}">Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Hi {{ request.user.username }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item {% if section == 'register' %}active{% endif %}">
              <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
            </li>
            <li class="nav-item {% if section == 'login' %}active{% endif %}">
              <a class="nav-link" href="{% url 'login' %}">Sign In</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="container pb-5">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success" role="alert">{{ message|safe }}</div>
        {% endfor %}
      {% endif %}
    </div>

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">
        {% block content %}
        {% endblock %}
      </div>

    {% if request.user.is_authenticated %}
      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        {% block search_widget %}
        {% endblock %}

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    {% if view.kwargs.username %}
                      <a href="{% url 'images:list' username=view.kwargs.username %}">Photos</a>
                    {% else %}
                      <a href="{% url 'images:list' username=request.user.username %}">Photos</a>
                    {% endif %}
                  </li>
                  <li>
                    {% if view.kwargs.username %}
                      <a href="{% url 'places:list' username=view.kwargs.username %}">Places</a>
                    {% else %}
                      <a href="{% url 'places:list' username=request.user.username %}">Places</a>
                    {% endif %}
                  </li>
                  <li>
                    {% if view.kwargs.username %}
                      <a href="{% url 'articles:list' username=view.kwargs.username %}">Articles</a>
                    {% else %}
                      <a href="{% url 'articles:list' username=request.user.username %}">Articles</a>
                    {% endif %}
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Tips</a>
                  </li>
                  <li>
                    <a href="#">Forum</a>
                  </li>
                  <li>
                    <a href="#">Plan your trip</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>
    {% endif %}

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5" style="background-color: #a5caf1;">
    <div class="container">
      <p class="m-0 text-center text-black">Copyright &copy; TravelBlog 2021</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
    });
  </script>
  
</body>

</html>