comments/urls.py
from django.urls import path
from django.views.decorators.http import require_POST

from . import views

app_name = "comments"

urlpatterns = [
    path(
        "comment/<model_name>/<int:pk>/",
        require_POST(views.CreateCommentView.as_view()),
        name="create_comment",
    ),
    path(
        "sub_comment/<model_name>/<int:pk>/",
        require_POST(views.CreateSubCommentView.as_view()),
        name="create_sub_comment",
    ),
]

images/urls.py
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path("add/<int:place_id>/", views.AddImageView.as_view(), name="add"),
    path("delete/<int:pk>/", views.DeleteImageView.as_view(), name="delete"),
    path("list/<str:username>/", views.ImageListView.as_view(), name="list"),
    path("<int:pk>/<slug:slug>/", views.ImageDetailView.as_view(), name="detail"),
]

travelblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("images/", include("images.urls", namespace="images")),
    path("places/", include("places.urls", namespace="places")),
    path("articles/", include("articles.urls", namespace="articles")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("", include("account.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from account.models import User


class CommentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class Comment(models.Model):
    author = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    objects = CommentManager()
    commented_obj_ct = models.ForeignKey(
        ContentType, related_name="comments", on_delete=models.CASCADE
    )
    commented_obj_id = models.PositiveIntegerField()
    commented_obj = GenericForeignKey("commented_obj_ct", "commented_obj_id")

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Comment by {self.author.username} on {self.commented_obj}"


class SubComment(models.Model):
    main_comment = models.ForeignKey(
        Comment, related_name="sub_comments", on_delete=models.CASCADE, null=True
    )
    author = models.ForeignKey(
        User, related_name="sub_comments", on_delete=models.CASCADE
    )
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    objects = CommentManager()

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Comment by {self.author.username} on {self.main_comment.author.username} comment"

comments/forms.py
from django import forms

from .models import Comment, SubComment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["body"]


class SubCommentForm(forms.ModelForm):
    class Meta:
        model = SubComment
        fields = ["body", "main_comment"]
        widgets = {"main_comment": forms.HiddenInput}

comments/views.py
from django.views.generic import FormView

from .forms import CommentForm, SubCommentForm
from .mixins import CreateCommentMixin


class CreateCommentView(CreateCommentMixin, FormView):
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.commented_obj = self.object
        comment.save()
        return super().form_valid(form)


class CreateSubCommentView(CreateCommentMixin, FormView):
    form_class = SubCommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

comments/templates/comments/comment/comments.html
{% load crispy_forms_tags %}
{% load comments %}

<!-- Comments Form -->
<div class="card my-4">
<h5 class="card-header">Leave a Comment:</h5>
<div class="card-body">
    <form action="{% url 'comments:create_comment' object|model_name object.id %}" method="post">
      {{ comment_form|crispy }}
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
</div>

{% for comment in comments %}
  <div class="media mb-4">
    <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
    <div class="media-body">
        <h5 class="mt-0">{{ comment.author.username }}</h5>
        {{ comment.body }}

        <form action="{% url 'comments:create_sub_comment' object|model_name object.id %}" method="post">
          {{ sub_comment_form|crispy }}
          {% csrf_token %}
          <input type="hidden" name="main_comment" id="main_comment_id" value="{{ comment.id }}">
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>

        {% for sub_comment in comment.sub_comments.all %}
          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{ sub_comment.author.username }}</h5>
              {{ sub_comment.body }}
            </div>
          </div>  
        {% endfor %}
    </div>
  </div>
{% endfor %}