articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path("create/", views.CreateArticleView.as_view(), name="create"),
    path(
        "update/<int:pk>/<slug:slug>/", views.UpdateArticleView.as_view(), name="update"
    ),
    path("delete/<int:pk>/", views.DeleteArticleView.as_view(), name="delete"),
    path("dashboard/", views.ArticleListView.as_view(), name="dashboard"),
    path("list/<str:username>/", views.ArticleListView.as_view(), name="list"),
    path(
        "<int:pk>/<slug:slug>/",
        views.ArticleDetailView.as_view(),
        name="detail",
    ),
]

comments/urls.py
from django.urls import path
from django.views.decorators.http import require_POST

from . import views

app_name = "comments"

urlpatterns = [
    path(
        "comment/<model_name>/<int:pk>/",
        require_POST(views.CreateCommentView.as_view()),
        name="create_comment",
    ),
    path(
        "sub_comment/<model_name>/<int:pk>/",
        require_POST(views.CreateSubCommentView.as_view()),
        name="create_sub_comment",
    ),
]

images/urls.py
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path("add/<int:place_id>/", views.AddImageView.as_view(), name="add"),
    path("delete/<int:pk>/", views.DeleteImageView.as_view(), name="delete"),
    path("list/<str:username>/", views.ImageListView.as_view(), name="list"),
    path("<int:pk>/<slug:slug>/", views.ImageDetailView.as_view(), name="detail"),
]

travelblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("images/", include("images.urls", namespace="images")),
    path("places/", include("places.urls", namespace="places")),
    path("articles/", include("articles.urls", namespace="articles")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("", include("account.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.conf import settings
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.db import models
from django.urls import reverse
from django.utils import timezone

from places.models import Place


class ArticleManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(publish=True)

    def search_by_title(self, search_text, objects=None):
        vector = SearchVector("title")
        query = SearchQuery(search_text)
        if not objects:
            objects = self.get_queryset()
        return (
            objects.annotate(search=vector, rank=SearchRank(vector, query))
            .filter(search=search_text)
            .order_by("-rank")
        )


class Article(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="articles", on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True)
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.BooleanField(default=False)
    objects = models.Manager()
    pub_objects = ArticleManager()
    places = models.ManyToManyField(
        Place, through="ArticlePlace", related_name="articles"
    )

    class Meta:
        ordering = ("-published",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("articles:detail", args=[self.id, self.slug])


class ArticlePlace(models.Model):
    article = models.ForeignKey(
        Article, related_name="article_places", on_delete=models.CASCADE
    )
    place = models.ForeignKey(
        Place, related_name="article_places", on_delete=models.CASCADE
    )
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.article}:{self.place}"

comments/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from account.models import User


class CommentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class Comment(models.Model):
    author = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    objects = CommentManager()
    commented_obj_ct = models.ForeignKey(
        ContentType, related_name="comments", on_delete=models.CASCADE
    )
    commented_obj_id = models.PositiveIntegerField()
    commented_obj = GenericForeignKey("commented_obj_ct", "commented_obj_id")

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Comment by {self.author.username} on {self.commented_obj}"


class SubComment(models.Model):
    main_comment = models.ForeignKey(
        Comment, related_name="sub_comments", on_delete=models.CASCADE, null=True
    )
    author = models.ForeignKey(
        User, related_name="sub_comments", on_delete=models.CASCADE
    )
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    objects = CommentManager()

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Comment by {self.author.username} on {self.main_comment.author.username} comment"

articles/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.utils.text import slugify

from places.models import Place
from .models import Article, ArticlePlace


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "body", "publish"]

    def save(self, force_insert=False, force_update=False, commit=True):
        article = super().save(commit=False)
        article.slug = slugify(article.title)
        if commit:
            article.save()
        return article


class ArticlePlaceForm(forms.ModelForm):
    class Meta:
        model = ArticlePlace
        fields = ["place", "description"]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(ArticlePlaceForm, self).__init__(*args, **kwargs)
        self.fields["place"].queryset = Place.objects.filter(author=self.user)


BaseArticlePlacesFormSet = inlineformset_factory(
    Article, ArticlePlace, form=ArticlePlaceForm, can_delete=True
)


class ArticlePlacesFormSet(BaseArticlePlacesFormSet):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(ArticlePlacesFormSet, self).__init__(*args, **kwargs)

    def _construct_form(self, *args, **kwargs):
        kwargs["user"] = self.user
        return super(ArticlePlacesFormSet, self)._construct_form(*args, **kwargs)


class ArticleSearchForm(forms.Form):
    article_search = forms.CharField(label="Search", help_text="Search for articles")

comments/forms.py
from django import forms

from .models import Comment, SubComment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["body"]


class SubCommentForm(forms.ModelForm):
    class Meta:
        model = SubComment
        fields = ["body", "main_comment"]
        widgets = {"main_comment": forms.HiddenInput}

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from common.mixins import DisplayCounterMixin
from comments.mixins import CommentMixin
from .forms import (
    ArticleForm,
    ArticlePlacesFormSet,
    ArticleSearchForm,
)
from .models import Article


class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = "articles/article/list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data()
        data["article_search_form"] = ArticleSearchForm()
        return data

    def get_queryset(self):
        username = self.kwargs.get("username")
        if username:
            articles = Article.pub_objects.filter(author__username=username)
        else:
            articles = self.request.user.articles.all()
        if "article_search" in self.request.GET:
            article_search = self.request.GET["article_search"]
            articles = Article.pub_objects.search_by_title(
                article_search, objects=articles
            )
        return articles


class ArticleDetailView(
    LoginRequiredMixin, DisplayCounterMixin, CommentMixin, DetailView
):
    model = Article
    template_name = "articles/article/detail.html"


class CreateArticleView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = "articles/article/article_form.html"
    form_class = ArticleForm
    template_title = "Create Article"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["title"] = self.template_title
        if self.request.POST:
            data["article_places"] = ArticlePlacesFormSet(
                self.request.POST, instance=self.object, user=self.request.user
            )
        else:
            data["article_places"] = ArticlePlacesFormSet(
                instance=self.object, user=self.request.user
            )
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        article_places = context["article_places"]
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        if article_places.is_valid():
            article_places.instance = self.object
            article_places.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("articles:dashboard")


class UpdateArticleView(CreateArticleView, UpdateView):
    template_title = "Update Article"

    def get_success_url(self):
        return self.object.get_absolute_url()


class DeleteArticleView(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = "confirm_delete.html"

    def get_success_url(self):
        return reverse("articles:dashboard")

comments/views.py
from django.views.generic import FormView

from .forms import CommentForm, SubCommentForm
from .mixins import CreateCommentMixin


class CreateCommentView(CreateCommentMixin, FormView):
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.commented_obj = self.object
        comment.save()
        return super().form_valid(form)


class CreateSubCommentView(CreateCommentMixin, FormView):
    form_class = SubCommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

articles/templates/articles/article/article_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
  <div class="container pt-5">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        {{ article_places|crispy }}
        <input type="submit" value="Save">
    </form>

  </div>
{% endblock %}

articles/templates/articles/article/articles.html
{% load thumbnail %}

<div class="container pt-5">
    {% for article in article_list %}
      <a href="{{ article.get_absolute_url }}"><p>{{article.title}}</p></a>
      <div class="container">
        {% with image=article.article_places.first.place.images.first %}
          <a href="{{ image.get_absolute_url }}"><img src="{% thumbnail image.image 300x0 %}"></a>
          <a href="{{ image.get_absolute_url }}"></a><p>{{ image.title }}</p></a>
        {% endwith %}
        <p>{{ article.body|truncatewords:50 }}</p>
      </div>
      {% if article.author == request.user %}
        <a href="{% url 'articles:update' pk=article.id slug=article.slug %}"><p>Edit article</p></a>
      {% endif %}
    {% endfor %}
</div>

articles/templates/articles/article/comments.html
{% load crispy_forms_tags %}

<!-- Comments Form -->
<div class="card my-4">
<h5 class="card-header">Leave a Comment:</h5>
<div class="card-body">
    <form action="{% url 'articles:comment' object.id %}" method="post">
      {{ comment_form|crispy }}
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
</div>

{% for comment in comments %}
  <div class="media mb-4">
    <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
    <div class="media-body">
        <h5 class="mt-0">{{ comment.author.username }}</h5>
        {{ comment.body }}

        <form action="{% url 'articles:sub_comment' object.id %}" method="post">
          {{ sub_comment_form|crispy }}
          {% csrf_token %}
          <input type="hidden" name="main_comment" id="main_comment_id" value="{{ comment.id }}">
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>

        {% for sub_comment in comment.sub_comments.all %}
          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{ sub_comment.author.username }}</h5>
              {{ sub_comment.body }}
            </div>
          </div>  
        {% endfor %}
    </div>
  </div>
{% endfor %}

articles/templates/articles/article/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Article{% endblock %}

{% block content %}
    {% if article.author == request.user %}
      <a href="{% url 'articles:dashboard' %}"><p>Back to your articles</p></a>
      <a href="{% url 'articles:update' pk=article.id slug=article.slug %}"><p>Edit article</p></a>
      <a href="{% url 'articles:delete' pk=article.id %}"><p>Delete article</p></a>
    {% endif %}
    <h2 class="mt-4">{{ article.title }}</h2>
    <p class="lead">
        by
        <a href="{{ article.author.get_absolute_url }}">{{ article.author.username }}</a>
    </p>
    <hr>
    <p>Posted on {{ article.updated }} </p>
    <p>Number of displays: {{number_of_displays}}</p>
    <hr>
    <p class="lead">{{ article.body }}</p>
    {% with places=article.article_places.all %}
      {% for place in places %}
        {% for image in place.place.images.all %}
          <div class="img-fluid rounded" class="container">
            <a href="{{ image.get_absolute_url }}"><img src="{% thumbnail image.image 500x0 %}"></a>
            <a href="{{ image.get_absolute_url }}"></a><p>{{ image.title }}</p></a>
          </div>
        {% endfor %}
        <hr>
        <blockquote class="blockquote">
            <p class="mb-0">{{ place.description }}</p>
        </blockquote>
      {% endfor %}
    {% endwith %}
    <hr>

    {% include "comments/comment/comments.html" with comment_form=comment_form comments=comments object=article %}

{% endblock %}

articles/templates/articles/article/list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_tags %}

{% block title %}{{ view.kwargs.username }} articles{% endblock %}

{% block content %}
  {% if not view.kwargs.username %}
    <a href="{% url 'places:create' %}"><p>Add place you have visited</p></a>
    <a href="{% url 'articles:create' %}"><p>Create story trip with visited places</p></a>
    <a href="{% url 'articles:dashboard' %}"><p>View my stories</p></a>
  {% endif %}

  {% include "articles/article/articles.html" with article_list=article_list username=view.kwargs.username %}
{% endblock %}

{% block search_widget %}
  <!-- Search Widget -->
  <div class="card my-4">
    <h5 class="card-header">Search</h5>
    <div class="card-body">
      <div class="input-group">
        <form method="get">
          {{ article_search_form|crispy }}
          <input type="submit" value="Search">
        </form>
      </div>
    </div>
  </div>
{% endblock %}