images/urls.py
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path("add/<int:place_id>/", views.AddImageView.as_view(), name="add"),
    path("delete/<int:pk>/", views.DeleteImageView.as_view(), name="delete"),
    path("list/<str:username>/", views.ImageListView.as_view(), name="list"),
    path("<int:pk>/<slug:slug>/", views.ImageDetailView.as_view(), name="detail"),
]

places/urls.py
from django.urls import path
from django.views.decorators.http import require_POST

from . import views

app_name = "places"

urlpatterns = [
    path(
        "add_image/<int:pk>/",
        require_POST(views.AddImageView.as_view()),
        name="add_image",
    ),
    path("create/", views.CreatePlaceView.as_view(), name="create"),
    path(
        "update/<int:pk>/<slug:slug>/", views.UpdatePlaceView.as_view(), name="update"
    ),
    path("delete/<int:pk>/", views.DeletePlaceView.as_view(), name="delete"),
    path("<str:username>/data.geojson", views.MapLayer.as_view(), name="data"),
    path("list/<str:username>/", views.PlaceListView.as_view(), name="list"),
    path("<int:pk>/<slug:slug>/", views.PlaceDetailView.as_view(), name="detail"),
]

travelblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("images/", include("images.urls", namespace="images")),
    path("places/", include("places.urls", namespace="places")),
    path("articles/", include("articles.urls", namespace="articles")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("", include("account.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/models.py
from django.conf import settings
from django.contrib.gis.db import models
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.urls import reverse


class PlaceManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()

    def search_by_name(self, search_text, objects=None):
        vector = SearchVector("name")
        query = SearchQuery(search_text)
        if not objects:
            objects = self.get_queryset()
        return (
            objects.annotate(search=vector, rank=SearchRank(vector, query))
            .filter(search=search_text)
            .order_by("-rank")
        )


class Place(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="places", on_delete=models.CASCADE
    )
    country = models.CharField(max_length=100, db_index=True)
    city = models.CharField(max_length=100, blank=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    location = models.PointField()
    created = models.DateTimeField(auto_now_add=True)
    objects = PlaceManager()

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("places:detail", args=[self.id, self.slug])

places/forms.py
from django import forms
from django.contrib.gis import forms as gis_forms
from django.forms.models import inlineformset_factory
from django.utils.text import slugify
from images.forms import AddImageForm
from images.models import Image

from .models import Place


class PlaceForm(forms.ModelForm):
    location = gis_forms.PointField(
        widget=gis_forms.OSMWidget(
            attrs={
                "map_width": 700,
                "map_height": 500,
                "default_lon": 21.0123297,
                "default_lat": 52.2315696,
                "default_zoom": 1,
            }
        )
    )

    class Meta:
        model = Place
        fields = ["country", "city", "name"]

    def save(self, force_insert=False, force_update=False, commit=True):
        place = super().save(commit=False)
        place.slug = slugify(place.name)
        if commit:
            place.save()
        return place


ImagesFormSet = inlineformset_factory(Place, Image, form=AddImageForm, can_delete=False)


class PlaceSearchForm(forms.Form):
    place_search = forms.CharField(label="Search", help_text="Search for places")

places/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.urls import reverse
from django.views.generic import DetailView, ListView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from djgeojson.views import GeoJSONLayerView

from comments.mixins import CommentMixin
from common.mixins import DisplayCounterMixin
from images.forms import AddImageForm
from .forms import ImagesFormSet, PlaceForm, PlaceSearchForm
from .models import Place


class PlaceListView(LoginRequiredMixin, ListView):
    model = Place
    template_name = "places/place/list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data()
        data["place_search_form"] = PlaceSearchForm()
        return data

    def get_queryset(self):
        username = self.kwargs.get("username", self.request.user.username)
        places = super().get_queryset().filter(author__username=username)
        if "place_search" in self.request.GET:
            place_search = self.request.GET["place_search"]
            places = Place.objects.search_by_name(place_search, places)
        return places


class PlaceDetailView(
    LoginRequiredMixin, DisplayCounterMixin, CommentMixin, DetailView
):
    model = Place
    template_name = "places/place/detail.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        data["add_image_form"] = AddImageForm()
        return data


class CreatePlaceView(LoginRequiredMixin, CreateView):
    model = Place
    template_name = "places/place/place_form.html"
    form_class = PlaceForm
    template_title = "Create Place"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["title"] = self.template_title
        if self.request.POST:
            data["images_form"] = ImagesFormSet(
                self.request.POST, self.request.FILES, instance=self.object
            )
        else:
            data["images_form"] = ImagesFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        images_form = context["images_form"]
        if not images_form.is_valid():
            return super().form_invalid(form)
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.location = form.cleaned_data["location"]
        self.object.save()
        if images_form.is_valid():
            images_form.instance = self.object
            images = images_form.save(commit=False)
            for image in images:
                image.author = self.request.user
                image.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("places:list", args=[self.request.user.username])


class UpdatePlaceView(CreatePlaceView, UpdateView):
    template_title = "Update Place"

    def get_success_url(self):
        return self.object.get_absolute_url()


class DeletePlaceView(LoginRequiredMixin, DeleteView):
    model = Place
    template_name = "confirm_delete.html"

    def get_success_url(self):
        return reverse("places:list", args=[self.request.user.username])


class MapLayer(LoginRequiredMixin, GeoJSONLayerView):
    model = Place
    geometry_field = "location"

    def get_queryset(self):
        username = self.kwargs.get("username", self.request.user.username)
        return super().get_queryset().filter(author__username=username)


class AddImageView(SingleObjectMixin, FormView):
    model = Place
    template_name = "places/place/detail.html"
    form_class = AddImageForm

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        image = form.save(commit=False)
        image.author = self.request.user
        image.place = self.object
        image.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.get_absolute_url()

places/templates/places/place/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}Place Detail{% endblock %}

{% block content %}
  <div class="container pt-5">
    <a href="#"><p>Places</p></a>
    <br>
    <p>{{ place.country }}</p>
    <p>{{ place.locality }}</p>
    <p>{{ place.name }}</p>
    <div class="container">
      {% for image in place.images.all %}
        <a href="{{ image.get_absolute_url }}"><img src="{% thumbnail image.image 500x0 %}"></a>
        <a href="{{ image.place.get_absolute_url }}"><p>{{ image.title }}</p></a>
        {% if image.author == request.user %}
          <a href="{% url 'images:delete' pk=image.id %}"><p>Delete image</p></a>
        {% endif %}
      {% endfor %}

      {% with related_articles=place.article_places.all %}
        {% if related_articles %}
          <p>Related articles</p>
          {% for article_place in related_articles %}
            <a href="{{ article_place.article.get_absolute_url }}"><p>{{ article_place.article.title }}</p></a>
          {% endfor %}
        {% endif %}
      {% endwith %}

      {% if place.author == request.user %}
        <form action="{% url 'places:add_image' place.id %}" method="post">
          {{ add_image_form|crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">Add image</button>
        </form>
        <br>
        <a href="{% url 'places:update' pk=place.id slug=place.slug %}"><p>Update place</p></a>
        <a href="{% url 'places:delete' pk=place.id %}"><p>Delete place</p></a>        
      {% endif %}
      <p>Number of displays: {{number_of_displays}}</p>
    </div>
  </div>

  {% include "comments/comment/comments.html" with comment_form=comment_form comments=comments object=place %}

{% endblock %}

places/templates/places/place/list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load leaflet_tags %}

{% block head %}
  {% leaflet_js %}
  {% leaflet_css %}
{% endblock %}

{% block title %}Visited Places{% endblock %}

{% block content %}
  <div class="container pt-5">
    {% if view.kwargs.username == request.user.username %}
      <a href="{% url 'places:create' %}"><p>Add place you have visited</p></a>
      <a href="{% url 'articles:create' %}"><p>Create story trip with visited places</p></a>
    {% endif %}

    <div class="container pt-3">
      <p>Visited Places</p>
      {% leaflet_map "main" callback="main_map_init" %}
    </div>

    {% include "places/place/places.html" with place_list=place_list %}
  </div>

  <script type="text/javascript">
    function main_map_init (map, options) {
        var dataurl = '{% url "places:data" username=view.kwargs.username %}';
        // Download GeoJSON via Ajax
        $.getJSON(dataurl, function (data) {
            // Add GeoJSON layer
            L.geoJson(data).addTo(map);
  });
      }
  </script>

{% endblock %}

{% block search_widget %}
  <!-- Search Widget -->
  <div class="card my-4">
    <h5 class="card-header">Search</h5>
    <div class="card-body">
      <div class="input-group">
        <form method="get">
          {{ place_search_form|crispy }}
          <input type="submit" value="Search">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

places/templates/places/place/place_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head %}{{ form.media }}{% endblock %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
  <div class="container pt-5">
    <form enctype="multipart/form-data" method="post">
        {{ form|crispy }}
        {{ images_form|crispy }}
        {% csrf_token %}
        <input type="submit" value="Add Place">
    </form>
  </div>
{% endblock %}

places/templates/places/place/places.html
{% load thumbnail %}

<div class="container pt-5">
  {% for place in place_list %}
    <p>{{ place.country }}</p>
    <p>{{ place.locality }}</p>
    <a href="{{ place.get_absolute_url }}"><p>{{ place.name }}</p></a>
    {% for image in place.images.all %}
      <div class="container">
        <a href="{{ image.get_absolute_url }}"><img src="{% thumbnail image.image 300x0 %}"></a>
        <a href="{{ image.get_absolute_url }}"></a><p>{{ image.title }}</p></a>
      </div>
    {% endfor %}
  {% endfor %}
</div>